### ISSUE TITLE
Anonymous input for offline debate

### ISSUE THREAD

**Issue by jwrosewell** [w3c/process#469] opened 2020-12-16 19:56 UTC
A method is needed to provide feedback anonymously in offline forums. The reliance on GitHub issues, and the need to accept GitHub terms and conditions makes this impractical currently.

Again, in light of comments about bullying within the organisation by larger companies, this would help to prevent any potential pressure from a larger company affecting feedback given.

**Comment by cwilso** [comment] 2020-12-16 21:30
James, if you are going to continue to refer to "comments about bullying within the organisation by larger companies," as you have repeatedly pointed at Google, I'm going to have to ask you to supply actual references, because I am feeling deliberately harassed and targeted without any data that supports your assertions.  You have repeatedly raised the threat of anti-trust and collusion (e.g. https://discourse.wicg.io/t/proposal-federated-learning-of-cohorts-floc/4473/6), in ways intended to disrupt open discussion of problems that face the web (such as how to improve user privacy on the web), and your continued calling out of anti-trust concerns and "bullying within the organisation by larger companies" in close proximity to your specific references to Google (e.g. https://www.adexchanger.com/data-driven-thinking/what-the-floc-dont-be-a-sheep/) impugn both Google's motives and behavior, as well (by extension) my own personal behavior and reputation as Google's AC representative.  If you do not mean to refer to Google, say so.  If you do mean to refer to Google, please point to references (pointing the W3C Team to them to follow up is enough, as I have confidence in both their discretion and their honesty, and I am in fact sensitive to concerns about bullying behavior).

If I have engaged in behavior that is perceived as bullying, I want to know about it, and repair my behavior.  If someone else from Google is perceived as bullying, it is my responsibility to follow up on that.  The W3C has a code of ethics and professional conduct, as well as an ombudsperson program for precisely this kind of concern.

**Comment by fantasai** [comment] 2020-12-17 03:47
I believe all WGs have their own dedicated mailing list, and if you were to post a message to such a list with feedback with the caveat that you are unable to post through GitHub the WG should be responsible for handling such feedback.

If you want to provide such feedback even more anonymously, you can ask someone to forward it for you "from an anonymous commenter". I imagine any W3C Team member would be willing to do so, provided such feedback were provided in good faith and in conformance with the Code of Conduct.

**Comment by chaals** [comment] 2020-12-17 05:35
There is a fundamental incompatibility between anonymous input and the Patent Policy. That is why it is inappropriate in general for people to forward others' technical contributions. It would be feasible to write a specific process for Team members to forward proposals anonymously.

Where a proposal is purely about inappropriate behaviour, the ombuds system already allows for anonymity.

Where there is an aspect of any proposal that bears on what is discussed in a Working Group (which seems to feature in many of your recent spate of issues @jwrosewell), I would suggest being very reluctant to assume something is not a technical argument. Leaving something out, as much as putting something into a technical specification actively shapes the resulting specification so it is hard to determine when an argument does not have a technical aspect, and the ombuds system is not an appropriate path for making technical decisions.

**Comment by chaals** [comment] 2020-12-17 05:48
(I'm not sure which "comments about bullying" you are referring to, but vague assertions that this happens are generally inappropriate, as they effectively call into question the behaviour of a variety of members, without providing any with an effective opportunity to respond. In other words, they are often themselves a bullying tactic.)

**Comment by jwrosewell** [comment] 2020-12-17 14:27
In response to @cwilso in this thread and in relation to my initial post on [FLoC](https://discourse.wicg.io/t/proposal-federated-learning-of-cohorts-floc/4473/9) following initial analysis of the [Texas vs Google](https://github.com/w3c/w3process/files/5709978/Texas.vs.Google.20201216_1.Complaint.Redacted.pdf) [10 US States] filing on 16th December 2020.

You are a member of W3C as a representative of Google – when you say things like “Speaking for myself and in my role as WICG chair” you only draw attention to the conflict of interest you have. One of my points is that the proposer of a position should not be a chair on the committee considering that proposal - is that so radical? 

We cannot distance ourselves from our employers, particularly when our roles are influential within our organisations; that is why we are appointed to the W3C isn’t it? I trust you would agree the web is important to Google and as the leader of Google within the standards body for the web anything you say in relation to the web would reasonably be expected to represent the position of Google.

You make a bunch of points about the low bar for getting into incubation. I agree. But my point is that the bar is too low. Google publish and put forward proposals that are contrary to the fundamental principles of a free and open web and are designed to create a walled garden. They should not be dignified by any discussion at W3C. W3C is dedicated to interoperability and openness and your proposals are about closing down the open web.  As 10 US States put it in their filing against Google yesterday: 

“228. Google’s decision to phase out third-party cookies on Chrome only increases the information asymmetries, leaving publishers with fewer alternatives other than Google’s user data. Because access to user data is only available on the or through Google intermediaries, Google’s decision to shut down third-party cookies on Chrome increases the information asymmetries between its exchange and other exchanges such as those in header bidding.”
  
You suggest that I am saying that “many people are saying” that Google has largely ignored the feedback that Google has been provided. That’s right- but they won’t speak out for fear of retribution. In the current situation Google are unilaterally making changes to the web in practice. For someone to complain publicly would be to associate their company with a position contrary to Google's. Google are so dominant and impact so many stakeholder’s fortunes that such a position cannot be sanctioned by their corporate governance process and that person and company remains silent. This is understandable given Google’s commercial importance. But nothing is being done to address the problem at W3C. As the 10 US States put it: 

“227. Given the extraordinary information Google has on every consumer, the threat of withholding that information from publishers forecloses competition.” And “….Google is able to use this massive information advantage strategically to harm any publisher who refuses to use its intermediaries…”

Google badging these changes "privacy" has further increased the barrier to going public because a complainant would be seen to take a position that is perceived to be in some way anti privacy. How is it in fact anti-privacy? I believe that true way that privacy can be protected is through an open web with open competition. The contrast between a privacy protecting, competitive, open web, which I support, and Google’s data mining monopoly could not be greater. 

As the 10 states put it: 

“140. Google’s entire business model is to collect comprehensive data about every user in the service of brokering targeted ad sales. It then uses privacy concerns as an excuse to advantage itself over its competitors. For example, Google’s stated reason for cutting off publishers’ user IDs is protecting users’ privacy, but Google does not protect users’ privacy when doing so harms Google. Google encrypts publisher ad server user IDs but uses the same user ID information for Google’s benefit, thus preventing consumers from obtaining the privacy benefits associated with encrypted from Google itself. The planned elimination of third-party cookies from Google’s dominant browser, Chrome, is also justified on privacy grounds, but the effect is to increase information asymmetries between Google and its competitors.”

I am suggesting changes that would allow members of W3C to speak out without fear of reprisal. For any democracy to function effectively we typically cast are polls in the secrecy of the polling booth –why not at W3C? This is not currently possible in practice in the WICG.

You make the point that you are actively trying to seek common ground. We are keen on finding that common ground, but it has to be about changes that support the open web, interoperability and improved functioning of the web for everyone- not just Google. 

It is for this reason, after much discussion and soul searching, along with many other people [Marketers for an Open Web](https://marketersforanopenweb.com/) was setup. An organisation must have at least one Director and I felt as the majority owner and leader of 51Degrees with the support of my shareholders I would take that role and in doing so become the spokesperson. So afraid are supporters of reprisals they have chosen to remain anonymous. Between us we work with more than 21,000 advertisers and nearly 6 million individual websites in more than 50 countries, jointly serving over 320 billion advertising impressions each year. The companies have a combined workforce of over 10,000 employees and combined revenues in excess of $4bn. More join every week. 

I have put forward proposals for changes to the W3C process that allow it to operate fairly and will help us reach agreement. That process has to allow members of W3C to make their views known – without fear of retribution.  We need a fair process before we can move on. We also need to recognise that the antitrust issues with Google proposals are very real.    

It is for all these reasons that I hope the UK CMA will use their interim measures powers to prevent what is known as “Privacy Sandbox” within WICG from being deployed until after parliament have been given the opportunity to implement legislation to regulate digital markets.

**Comment by michaelchampion** [comment] 2020-12-17 18:31
@jwrosewell , thanks for making it more explicit what all these issues are really about.  Here's my personal take on all this:

I got involved in W3C in the late 1990s as a representative of a small company, at the height of the "browser wars" between Netscape and Microsoft.  I was amazed to see that the *people* of Netscape and Microsoft worked well together at W3C despite the fact that their top leadership were litigating, appealing to regulators, and generally having an ugly fight.  It was clear to me as an outsider that people worked together at W3C because  their customers were telling them that it was in their best interest to cooperate to find solutions  all could live with.  

W3C thrived during that period and began to solidify the HTML/CSS/DOM core web platform for 2 main reasons: It stayed out of the legal/political ugliness, focusing on facilitating technical consensus. Likewise it promoted the values of interoperability, accessibility, and internationalization that were not yet deeply entrenched in engineering culture.   W3C's founder and Director seldom directly intervened with his Benevolent Dictator power, but helped create a culture similar to that described in IETF’s famous motto “ We reject: kings, presidents and voting.     We believe in: rough consensus and running code.”

I don’t get the sense from the recent issues that the adtech community at W3C has internalized that culture.  Instead, I get the sense  they want to use W3C as a  tool in a  political/legal war on browsers that block tracking cookies by default, not as a venue for finding common ground to define an ad-supported without levels of surveillance that many find unacceptable.  And if finding common ground across the W3C community really is the goal,  tactics such as appeals to the authority of government bodies and veiled threats of litigation are extremely counterproductive.  

As far as I can tell,  this is fundamentally a Values conversation: Is "free ad supported content" or “privacy right to avoid surveillance" more important to the larger W3C community? Or perhaps both are equally important and the dominant value is consensus (W3C shouldn’t issue standards unless all stakeholder advocates agree on them, no consensus means no standard).  Any outcome would probably drive away some current members, but those who remain would understand what they can and can’t hope to standardize at W3C.  

So for what it’s worth, and not representing any member’s position, I’d suggest:
- Closing most of the issues  numbered 467 to 482 because the Process Document isn’t the appropriate place to address them.  Many deal with the management of the Team, or the text of the Membership Agreement, or the operation of Community Groups, which are not defined in the Process. 
- @jwrosewell or like-minded folks might open new issues in this repo that suggest specific changes to the W3C Process that would mitigate concrete problems.  Matters that aren't covered by the Process might go to the AB's member-only repo, or AC-Forum, or (especially legal matters) to W3M privately.
-  Most importantly, **the AB and AC should have an explicit conversation about W3C’s core values,** and put a clear statement of those values into the foundational documents for the W3C “legal entity” they hope to launch in 2022.  Those who don’t accept that value statement presumably won’t sign the new member agreement. Those who do will have a clear sense of what to expect.

**Comment by TzviyaSiegman** [comment] 2020-12-18 19:24
Please note that "W3C strictly prohibits discrimination, intimidation, harassment, and bullying of any kind and on any basis." See https://www.w3.org/Consortium/cepc/ for more information about what that means.

**Comment by frivoal** [comment] 2020-12-21 00:38
> That process has to allow members of W3C to make their views known – without fear of retribution.

It already does: while normal conversation is expected to happen in the open, the formal objection process does allow a person to report a problem privately to the team without disclosing their identity to the broader world, and ask for a ruling on the question.

As discussed by @chaals in https://github.com/w3c/w3process/issues/469#issuecomment-747216676, there are inherent problems with discussing technological points anonymously, so this cannot be the primary venue for discussion, but it is already possible to raise a red flag and have the breaks pulled on advancement of a particular specification or working group without disclosing you identity to all if the Formal Objection handling process finds that you have a legitimate point.

We could add a note in the Formal Objection section of the process highlighting that it is possible to raise one privately, but given that there is already text to explain how to publicly share information when it was submitted privately, and nothing in the Process suggests that submitting a formal objection should be done publicly, so it should already be clear that submitting privately is a possibility. Moreover, the Process is explicit that in case of AC reviews, the the forms that allow for submission of feedback, including formal objections, must allow for private submission. And the forms actually in use do have that feature. So this is not merely a theoretical possibility, but one that is already implemented in our actual operations.

See https://www.w3.org/2020/Process-20200915/#WGArchiveMinorityViews for the formal objection reporting process, and https://www.w3.org/2020/Process-20200915/#confidentiality-change for how to publicly share information that was provided privately, and https://www.w3.org/2020/Process-20200915/#advisory-committee-review for the AC Review process, including a specific provision that it must be possible to provide answers that are visible only to the Team.

I believe this issue should be closed with no change, as the feature being asked for is already here.

**Comment by jwrosewell** [comment] 2020-12-23 12:33
@michaelchampion Thank you for the background and clarity. Please don’t misunderstand me. Both me and the organisations I’m involved with are pro privacy. We think the best option to protect privacy involve open markets and not data mining monopolies.

These issues are about compliance with established laws associated with technical standards which all standards bodies in Europe and the US must comply. I have opened an issue in relation to these requirements under “[upgrade antitrust provisions](https://github.com/w3c/w3process/issues/482)”.

20 years ago there were many web browsers, and considerably fewer publishers and people relying on the web.

Today there are 3 web browser engines, 4.5 billion people relying on the web, and millions of publishers supporting trillion dollar markets where some participants are themselves worth in excess of a trillion dollars. Further the [Texas vs Google](https://www.courtlistener.com/recap/gov.uscourts.txed.202878/gov.uscourts.txed.202878.1.0.pdf) pleading draws attention to the following: 

- the misrepresentation by Google of its actions;
- anticompetitive coordination or “privacy fixing” among competitors;
- a documented plan to create a walled garden to capture online publishers on the open internet and transform them into content creators generating revenue for Google on a completely closed platform—like YouTube content creators; and
- threaten the free and open internet through, among other things, Google’s proposed Chrome browser changes which are given legitimacy by the W3C.

If proved Apple and Facebook are also complicit in anticompetitive activities.

In August, I along with other concerned individuals took related issues to the Advisory Board (AB) to gain their advice and raise the profile of the concerns. A significant number of those I spoke with advised me to engage with regulators to address matters of competition as these are not matters for the W3C. I have since followed that advice and setup [Marketers for an Open Web](https://marketersforanopenweb.com/) to work with regulators to implement their remedies.

Others advised to bring issues that related to process here. I have done so. Closing the issues, I raised last week without understanding the compliance obligations W3C, it’s members and participants face would be negligent. Maybe the issues can be addressed via text changes to the process. Maybe we need to start with a simplified membership agreement and process. We need to be open to both possibilities.

Where matters require more significant reform I have discussed these with the appropriate W3C Team members. It is clear the way forward is open discussion among the members.

In relation to your question on Values.

> As far as I can tell, this is fundamentally a Values conversation: Is "free ad supported content" or “privacy right to avoid surveillance" more important to the larger W3C community?

Absolutely no one is asking this question. There is no question over people’s right to privacy. Privacy is a matter of compliance with the law for each participant.

This question is really; why should the only solutions being advanced at the W3C be those that concentrate more personal information and the revenue advantages that come with it into the walled gardens of a smaller number of US trillion dollar highly integrated members of an oligopoly? This isn’t a question of consensus, it’s a matter of compliance with competition law.

Other questions we need to be asking and answering include.

-	Why has the W3C adopted documents like the Security and Privacy questionnaire that actively discriminate against smaller players and advantage the most dominant? 
-	Has an environment closed to the discussion of market dynamics associated with technical standards helped create the problem?
-	Are we collaborators in the problems referred to in Texas vs Google? Google certainly make reference to collaboration at the W3C in their public statements.

Assuming W3C is to remain first and foremost a technical standards body these issues need to be addressed urgently, certainly in the first few months of 2021.

I welcome your advice but ask you not to mischaracterise the problem, my intentions, or ignore the obligations an international standards body for a resource used by half the people in the world must comply with.

**Comment by wseltzer** [comment] 2020-12-24 00:02
Allegations in a complaint are not proof. I hope that participants here can debate one another on the best ways to protect privacy, competition, interoperability, and other values without slinging legal allegations.

**Comment by frivoal** [comment] 2020-12-24 02:22
> This question is really; why should the only solutions being advanced at the W3C be those that concentrate more personal information and the revenue advantages that come with it into the walled gardens of a smaller number of US trillion dollar highly integrated members of an oligopoly?

> Other questions we need to be asking and answering include: 

The title of this issue is "Anonymous input for offline debate". Unless we stay reasonably focused on what the issue is, we have no hope of making progress. These other question may be interesting, but they are distinct questions. If you would like to explore them, please open separate issues, in the relevant groups (most of these questions don't seem to be a matter of Process)

As for this actual issue, I sand by what I said in https://github.com/w3c/w3process/issues/469#issuecomment-748698339: we already have what is being asked for, therefore there is nothing to do.

**Comment by jwrosewell** [comment] 2020-12-24 12:25
It would be fair and reasonable to agree that allegations that are not based on fact or evidence are not proof - they would merely be allegations. But the allegations in the Department of Justice case and states attorney general cases are based on well reported investigations with evidence and witness statements from many affected. Some sources of evidence are referred to in the pleadings and are redacted. Given also that the US cases also cover findings of fact in decisions that have been taken by the EU Commission - in the Android and Search cases- these are not mere allegations.
 
So while the courts have to determine the position in each case it is also a matter for the W3C to acknowledge and understand and take into account in determining its position on compliance with the law. Here we think that the fact that DOJ guidelines have changed recently should be a matter that is considered carefully by all.

@wseltzer With all this in mind do you agree that the threshold has now been reached for the W3C antitrust policy to apply? If not please can you explain what the threshold needs to be? Does the antitrust policy now need to be updated?

@frivoal if there is a more appropriate forum to discuss the matter of antitrust please advise where you would prefer to direct the dialogue. In relation to the specific issue the reality is that anonymous input is not supported in practice.

**Comment by frivoal** [comment] 2020-12-29 03:40
> if there is a more appropriate forum to discuss the matter of antitrust please advise where you would prefer to direct the dialogue.

I suspect speaking to the W3C's counsel would be appropriate. In any case, this group is not chartered to deal with such matters. Regardless of your motivations, if you have specific changes you would like to bring to the Process document, this place is appropriate. For general discussions of antitrust, it is not.

In this issue you have made no concrete suggestion of what you would like to change in the Process document. And for the problem statement itself:

> In relation to the specific issue the reality is that anonymous input is not supported in practice.

You're going to need to support that claim, as does not seem true to me.
* At various stages of the specification evolution, the Process requires [formally adressing](https://www.w3.org/2020/Process-20200915/#formal-address) all issues raised against the document. This includes issues reported by members of the general public who are not working group members, and is not conditioned on knowing their identity. For patent policy reasons, we do not take in substantive proposals from unidentified anonymous sources, but we do respond to issues raised against specifications by anyone, and neither sending an email nor a making a github comment requires you to disclose your identity. If github is not a practical venue for you due to their terms and conditions, groups can still be reached by email, even when that is not their preferred way of interacting.
* Chairs of various groups, as well as team contacts, are identified individuals who can be contacted privately, if you want to let them know that there's something the group should take into account without speaking to the group directly.
* Formal objections can be made privately, if concerns couldn't be addressed at an earlier stage.
* The ombuds system also allows participants to raise concerns privately.

So it is absolutely possible to make comments and have your input taken into account without disclosing your identity.

If you believe there is a specific form of anonymous comment that we ought to have but currently don't, please be clear about how that should work. Otherwise, there's nothing to be done here.

**Comment by wseltzer** [comment] 2020-12-30 15:14
@jwrosewell No, I don't see your citations as relevant to the discussions at hand, nor as reasons to interfere with technical discussion. Please stop opening and re-opening essentially the same issue.

**Comment by dwsinger** [comment] 2021-01-05 21:09
There seem to be some serious non-sequiturs here; for example, this [comment](https://github.com/w3c/w3process/issues/469#issuecomment-747470689) has a number of sentences starting "you" which don't seem to refer to anyone making any previous comment. 

Also, this is a group that manages the process document; which is what guides us as we develop technical standards. This is not a group of lawyers, and the mentions of laws etc. tends to have a chilling effect on debate. There are cases where mention of law is justified, but they are rare (e.g. in a recent issue, where someone asked that we always record all conversations, and the need fro consent in at least some jurisdictions was mentioned). Even then, I'd prefer that non-lawyers phrase questions (e.g. "could we check whether there are laws that require consent before recording?") rather than make statements.

Similarly, and I expect that once I point it out, you'll stop, vague mentions of "bullying" also have a chilling effect, as they give the undesirable and, I am sure, unwanted, impression that if someone disagrees with you, they will be accused of "bullying". If, in fact, pressure of any sort is being brought to bear on you, please bring it to an ombudsman under the CEPC.

We have robust reasons not to allow anonymous technical contribution, as it's important all ideas used be traceable to their origin, and fall under the umbrella of the patent policy. If you have justified concerns that you cannot make technical arguments without fear, you should not only get those concerns addressed (e.g. by contacting an ombudsman) but also talk to a team member, or a trusted colleague, to make sure that those technical concerns are nonetheless aired.

**Comment by jwrosewell** [comment] 2021-01-08 09:16
@dwsinger at least one comment has been deleted from this issue which I suspect explains your observation.

@dwsinger the bullying to which I refer as at an organisational level rather than an individual level. Some examples include;

1. lecturing participants but telling the world you're collaborating and debating with others; 
2. ignoring feedback and progressing anyway; 
3. presenting proposals in a way where market participants consider that proposal to be a "done deal" which then results in immediate loss for other market participants and gains for the proposer;
4. advancing so many proposals the rest of the eco-system can't keep up; and
5. not presenting facts and evidence to support your arguments whilst requesting others present their evidence.

(I have a great deal of evidence to support these claims most of which has already been made available or will be known to the engaged reader.) 

I've observed circular arguments concerning matters that are unrelated to process or technical standards at the W3C. When I joined the W3C one of the first matters I was asked to vote on was a public statement related to BLM. I was also pointed to a document titled "Ethical Web Principles". I took this to indicate that W3C considered and encouraged debate and engagement on a broad range of issues beyond technical standards and process. I also learned that documents such as the "[The Internet is for End Users](https://www.mnot.net/blog/2020/08/28/for_the_users)" by @mnot was held in high regard by many W3Cers. I trust I will be forgiven for operating under the impression that none technical standards and none process matters were in scope for debate and indeed such matters were exercising a significant number of W3C participants. In fact I believe the impact of technical standards setting and implementation of technical standards in practice is concerning a lot of people at the moment.

When considering these issues I start by consulting the Advisory Board (AB) to gain their advice. I was directed to this Process CG for most of the issues. Further before raising these issues I discussed them with W3C Team. I was similarly advised to direct process issues to Process CG.

I will explore your advice in relation to the ombudsman and I'm seeking further advice concerning the best way to raise these significant matters.

Returning to the topic of the issue - anonymous input for offline debate.

I understand the issue that might come up with patents when the proposal for a standard needs to have a traceable input. I guess that the issue that is at the heart of this discussion is that proposals are being put forward that are not about the creation of standards and “consensus" can then be derived from the silence of other members of the group or stakeholders unaware of the proposal. 

If the issue of how consensus is achieved in [472](https://github.com/w3c/w3process/issues/472) is resolved that might address this issue. I will also explore the ombudsman process to understand how it helps address this issue.

**Comment by jwrosewell** [comment] 2021-04-14 07:15
Given recent events, the W3C must now make a decision that will impact not only the future of the web, but the reputation of the W3C.

W3C process is designed for open collaboration and consensus on changes to interoperable standards to further the growth of the web. However, the example of how Google’s Privacy Sandbox proposed standards are progressing are publicly manipulating this process and promoting changes that would disproportionately impact the ability for smaller authors to continue to rely on supply chains to operate their businesses. This directly conflicts with the recently updated [design principles]( https://www.w3.org/TR/design-principles) for the web. TAG also recognize this in their report into [First Party Sets]( https://github.com/w3ctag/design-reviews/blob/main/reviews/first_party_sets_feedback.md) a component of Google’s Privacy Sandbox. The following quote is of most relevance.

> It is likely that this proposal only benefits powerful, large entities that control both an implementation and services.

In the report TAG also form concrete views on subjects well beyond engineering that I suspect lawmakers would find interesting.

> Considering that users ignore, or accept without reading, alerts like the EU cookie warning, it's unlikely that this approach could constitute meaningfully informed consent

While it is critical to protect people’s important privacy rights, the current approaches to balance user rights with the needs for interoperable functionality is “[not yet ready for prime time]( https://www.w3.org/TR/design-principles)” according to the TAG. However, even in the revised design principles there is growing risk to smaller organizations ability to continue to operate, should even consented and pseudonymized personal user data be unavailable to support web authors access to supply chain services that require such data.

Yet the more immediate threat to smaller web authors and the open web is how W3C is supporting Google’s Privacy Sandbox. Given the large collection of proposed changes, it is useful to focus on just a few to illustrate how these proposals threaten smaller web authors.  

Google has been developing its Federated Learning of Cohorts (FLoC) for over a year. Google first proposed Federated Learning of Cohorts (FLoC) in the Improving Web Advertising Business Group (IWA BG). Much of the debate occurs in the Web Incubation Community Group (WICG) from May 2020. It was not until [December 2020](https://discourse.wicg.io/t/proposal-federated-learning-of-cohorts-floc/4473/2) that another organisation publicly supported the proposal. 

Google had since moved to discuss timelines and origin trials following a great deal of publicity and industry persuasion outside the W3C. A handful of organisations showing support after so much time would fall short of “wide support” let alone “consensus”. Yet Google progressed almost unaltered.

Google asked the digital media industry to engage in the FLoC experiment. In January 2021 Google’s Chetna Bindra, a Google representative, published a widely [publicised blog](https://blog.google/products/ads-commerce/2021-01-privacy-sandbox/) post explaining that FLoC provides 95% conversions per dollar compared to the existing solution. When asked to [provide the working and evidence](https://github.com/w3c/web-advertising/issues/109) to support this claim Google have not done so. Instead they have obfuscated and engaged in verbal sessions where titbits of further information have been provided, but nothing of substance. We then learn from Michael Kleber of Google on [1st April 2021](https://www.w3.org/2021/04/01-web-adv-minutes.html) that the algorithm referred to in the January 2021 blog post is not in fact the same algorithm that is to be used in the experiment. Chetna Bindra confirmed in that meeting that Google would not retract the prior claim. Despite Deepak Ravichandran of Google’s email to W3C stating he wanted the truth of his experiment to be published, so as to resolve the prior misunderstanding (that he agreed at [IWA BG meeting 16th March]( https://www.w3.org/2021/03/16-web-adv-minutes.html)).

> Deepak: Trying to understand what would satisfy you?
>… If I write A/B experiment, and if it's unclear
>… then I will write that
>… what Brad said, we did not represent what we wrote incorrectly
>… perhaps it was interpreted differently
>… be clear about that
>… I want to be constructive; I will publish all the details
>… I will adhere to true scientific spirit

It seems clear that Google will not publish information required for others to validate the original “95%” claim.

To prevent a repeat of this sort of “stand off”, on 1st April 2021 I requested we agree a way of ensuring the [evidence can be presented](https://github.com/WICG/floc/issues/86) in such a way as to enable an impartial party to determine the impact of the experiment. The issue was immediately closed by Google’s Michael Kleber citing it was up to each experimenter to publish their results. These experiments are demonstrably market impacting and are therefore subject to the W3C [antitrust and competition guidance](https://www.w3.org/Consortium/Legal/2017/antitrust-guidance). 

Despite these issues Google releases on 30th March 2021 a new web site called [privacysandbox.com](https://privacysandbox.com/)(PS). The 30 proposals referenced have largely been ignored, although some aspects do appear to have been incorporated into the revised FLoC approach. Significantly for this group the link to “web standards” from the PS web site takes the reader to a W3C web page that states the following.

> W3C develops these technical specifications and guidelines through a process designed to maximize consensus about the content of a technical report, to ensure high technical and editorial quality, and to earn endorsement by W3C and the broader community.

This is misleading, and as a minimum the W3C must request that Google update the website to avoid presenting the impression to the reader that they are working on web standards.

The industry has accepted the narrative. I find the following panel session a very good example of how these issues are being interpreted by a wider non-technical group of business decision makers.

[Cookie-pocalypse: marketing & media effectiveness in a cookie-less world](https://wmg.wavecast.io/marketing-and-media-effectiveness-in-a-cookie-less-world/live)
 
I trust we can agree that the trust problems in social media described in the Netflix documentary the Social Dilemma and the Cambridge Analytica scandal are entirely unrelated to the standards of interoperability that form the web.

Another aspect of Privacy Sandbox is also being questioned more widely. [No evidence]( https://github.com/WICG/ua-client-hints/issues/215) has been provided in relation to the justification for changes to the User-Agent feature of HTTP. It seems that Google have joined the TAG in requiring evidence from other people [without presenting any themselves]( https://github.com/w3ctag/security-questionnaire/issues/83) to justify their position. Had the justification been readily available then it would have been published by now. Yet an experiment under WICG is progressing to production deployment and industry participants are forced to make substantial investments to adapt. Google have shown [no interest]( https://github.com/WICG/ua-client-hints/issues/176) in moving these, now fully deployed changes, into the W3C process.

In raising these issues, I have been repeatedly told that they are not appropriate topics for the W3C consensus process. However, by refusing to discuss the foreseeable impacts on smaller participants this suggests that the W3C endorses the proposals and their foreseeable impacts.   

Having followed the W3C ombuds process I can confirm that it is entirely ineffective in practice. There is no effective method of providing anonymous input.

As the W3C are hosting these discussions they are complicit in the harm being inflicted on the web calling into question not only the tolerance for bullying at an industrial scale, but also their commitment to the mission of the W3C and the membership agreement. The process of refining the process needs to urgently change to reflect the current reality.

**Comment by frivoal** [comment] 2021-04-15 13:41
@jwrosewell You have made your concerns about this general topic clear. However, this comment of yours is in an issue whose alleged purpose is to request the ability to give anonymous input for offline debate. It may be very relevant to your interests, but it does not appear to be relevant to the issue in which you posted it (at least I cannot find the connection). Various people have stated why they believe some measure of anonymity was already afforded in various cases, and why an general path to anonymous contributions was not practical. As far as I can see, you have neither agreed with nor countered these arguments, which is what I would expect in order to try and make progress here.

**Comment by jwrosewell** [comment] 2021-04-15 15:28
@frivoal These issues have been raised via the ombuds process. The ombudsperson has done nothing. 

As in this particular case I do not mind raising the subject publicly via online comments. I'm conscious earlier comments broadened the issues and deserved an update. 

I know many who share my views will not feel comfortable doing so publicly or online via comments, or even +1s. Many will consider the ombuds process daunting and would prefer a simple method to provide anonymous input. It seems this will only be possible where the issue raiser feels they can confide in group chairs or the W3C Team.

**Comment by frivoal** [comment] 2024-05-24 02:44
As per https://github.com/w3c/w3process/issues/469#issuecomment-748698339, https://github.com/w3c/w3process/issues/469#issuecomment-750708242, https://github.com/w3c/w3process/issues/469#issuecomment-748698339, and https://github.com/w3c/w3process/issues/469#issuecomment-820431109, I propose closing. This issue contains lots of side discussions about lots of things, but as to the main point, there has been no rebuttal in the past three and a half years of my claim that there is nothing to be done because the feature being asked for is already available (and as discussed above, going beyond that is undesirable, notably for patent policy reasons).

**Closed** 2024-10-09 14:51 UTC
Labels: Proposed to close
