### ISSUE TITLE
Registry report requirements

### ISSUE THREAD

**Issue by chrisn** [w3c/process#725] opened 2023-03-30 18:26 UTC
The requirements for [publishing a registry report or registry section](https://www.w3.org/Consortium/Process/Drafts/#reg-pub) includes:

> Clearly label the registry report/section, its tables, and its registry definitions as such, including a link to §6.5 The Registry Track in this Process.

Why do registry reports and not other W3C Technical Reports (Rec or Note track reports) need to include a link to the relevant Process section? Is this requirement necessary for registries or could it be relaxed?

For context, see discussion in https://github.com/w3c/webcodecs/issues/644 (although the conversation there relates more to tooling and whether there's a need for a "draft registry" document status).

**Comment by dwsinger** [comment] 2023-03-30 18:55
I think we wanted, at least for a while, to differentiate Registries (as defined in the Process) from registries that are already being run on previous un-definitions, that's all. So, something like "This section defines the [Registry](https://www.w3.org/2021/Process-20211102/#registries) for synthetic fur colors".

**Comment by chrisn** [comment] 2023-03-30 18:59
Thank you, that makes perfect sense.

**Comment by tidoust** [comment] 2023-03-31 05:31
While the Process itself does not require a link in all cases, publication rules do, see for instance https://www.w3.org/pubrules/doc/rules/?profile=WD#publish

The link required by publication rules in the Status of This Document section is to [6.1 Types of Technical Reports](https://www.w3.org/2021/Process-20211102/#recs-and-notes).

The Process rather requires an explicit link to [6.5 The Registry track](https://www.w3.org/2021/Process-20211102/#registries) for Registries. Question is: can we consider that the link to 6.1 in the SOTD meets (at least the spirit of) this requirement? If so, could the requirement be relaxed in the Process?

Publication rules could perhaps be amended otherwise. This is being tracked in https://github.com/w3c/specberus/issues/1713

**Comment by frivoal** [comment] 2024-04-19 07:29
@chrisn, based on your response in https://github.com/w3c/w3process/issues/725#issuecomment-1490783825, I think you're ok with closing this issue as a question answered. Could you confirm?

**Comment by chrisn** [comment] 2024-04-19 09:13
My question was answered, but the one @tidoust raises still needs addressing. I suggest that the existing link to 6.1 (as applied by the current publication rules) should be enough, as the text in SOTD clearly identifies the document is on the Registry Track, and 6.1 links through to 6.5.

**Comment by frivoal** [comment] 2024-04-19 09:31
I think linking to 6.1 from SOTD may be alright for Registry reports. I'm not sure the indirection is helpful, but I don't think I'd object.

For the registry tables and registry definitions of an embedded registry, linking to something as generic as 6.1 doesn't seem very helpful. That said, I don't think pubrules can reasonably check for that. The consequence is rather the other way around: if a portion of a REC track document was intended to be (part of) an embedded registry, but forgot to spell it out (including the link), then it is governed by the usual REC track rules, without registry specific provisions.

**Comment by chrisn** [comment] 2024-04-19 10:26
The main benefit of the indirection seems to be not requiring a change to the publication rules for registry reports, but I can see the complexity with embedded registries, and I agree linking to 6.1 there is less helpful.

The other route, of course, is to update the publication rules as suggested in https://github.com/w3c/w3process/issues/725#issuecomment-1491319659, without changes to the Process.

**Closed** 2024-11-27 02:43 UTC
Labels: Commenter Response Pending, Closed: Question answered, Proposed to close
